### ISSUE TITLE
Vehicle detection

### ISSUE THREAD

**Issue by GSunilc** [datasciencecompleteguide/Machine-Learning#43]
File "D:\vehicle 2\import", line 13, in <module> grey-cv2.cvtColor (frame1, cv2.COLOR_BGR2GRAY)

I am getting this error ,but I am using recorded mp4 video.p lz help me

**Comment by datasciencecompleteguide** [comment]
Hey,
Post the complete code and the error!!

**Comment by GSunilc** [comment]
import cv2
import numpy as np
# Web camera
cap=cv2.VideoCapture ('video.mp4')
min_width_react=80    #min width reactangle 
min_height_react=80   #min width reactangle
count_line_postion= 550
# Initialize Substructor
algo=cv2.createBackgroundSubtractorMOG2()
while True:
    ret,frame1=cap.read()
    grey=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
    blur=cv2.GaussianBlur(grey,(3,3),5)
  #  applying on each frame
    img_sub=algo.apply(blur)
    dilat=cv2.dilate(img_sub,np.ones((5,5)))
    kernel=cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
    dilatada=cv2.morphologyEx(dilat,cv2.MORPH_CLOSE,kernel)
    dilatada=cv2.morphologyEx(dilatada,cv2.MORPH_CLOSE, kernel)
    counterSahpe,h=cv2.findContours(dilatada,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

    cv2.line(frame1,(25,count_line_postion),(1200,count_line_postion),(255,127,0),3)
    for (i,c) in enumerate(counterSahpe):
        (x,y,w,h)=cv2.boundingRect(c)
        validate_counter=(w>= min_width_react) and (h>= min_height_react)
        if not validate_counter:
          continue
        cv2.rectangle(frame1,(x,y),(x+w,y+h),(0,225,0),2)
        cv2.imshow('video original',frame1)
        if cv2.waitKeyEx(1)==13:
          break
    cv2.destroyAllWindows()
    cap.release()


It runs well in 1st iteration and getting error after that.

**Comment by GSunilc** [comment]
Bro is their any specific height and angle in which camera should be installed.help me in this plz it's urgent.....

**Comment by GSunilc** [comment]
Bro is their any specific height and angle in which camera should be installed.help me in this plz it's urgent.....

**Comment by datasciencecompleteguide** [comment]
if you are detecting the moving vehicles number plate then make sure that you capture the frames and try your detection model on every frame then you can check in which frame range you are getting the best answer....capture those frames frequently.

Also, one more possible thing that you can do is try applying different models and compare the results. Keep the best possible result.

**Comment by GSunilc** [comment]
Thanks for the response.i already posted my code have you gone through it
and find any issue.
It's urgent for me .plz help me.
