### ISSUE TITLE
faceDetection

### ISSUE THREAD

**Issue by Milind3707** [datasciencecompleteguide/Machine-Learning#49]
File "C:/Users/admin/OneDrive/anlisys/Desktop/facetrain2.py", line 10, in <module>
    facesdetected,gray_img = fr.faceDetection(test_img)
AttributeError: module 'face_recognition' has no attribute 'faceDetection'
  

sir please error ko kaise solve kare iske uper video banao

**Comment by datasciencecompleteguide** [comment]
> File "C:/Users/admin/OneDrive/anlisys/Desktop/facetrain2.py", line 10, in facesdetected,gray_img = fr.faceDetection(test_img) AttributeError: module 'face_recognition' has no attribute 'faceDetection'
> 
> sir please error ko kaise solve kare iske uper video banao

can you plss send me the code in which you are facing this issue!!...So, that i can get better insight and be able to solve this error as early as possible
